from __future__ import annotations

from datetime import datetime, timezone

from .models import (
    AuditLog,
    Exercise,
    ExercisePhase,
    ExerciseStatus,
    Inject,
    InjectPriority,
    InjectStatus,
    InjectType,
    ReviewItemType,
    StudioReviewItem,
    StudioReviewStatus,
    TimelineEvent,
    TimelineEventType,
    User,
    UserRole,
)
from .registry import ForgeStudioRegistry


def create_mock_registry() -> ForgeStudioRegistry:
    """Create safe local mock data for the first Forge Studio web app."""

    exercise = Exercise(
        id="mountain-exercise-3-27",
        name="Mountain Exercise 3-27",
        description="Bridgeport EXCON service-level mountain warfare exercise.",
        status=ExerciseStatus.ACTIVE,
        phase=ExercisePhase.EXECUTION,
        start_date=datetime(2027, 3, 27, 8, 0, tzinfo=timezone.utc),
        end_date=datetime(2027, 3, 27, 18, 0, tzinfo=timezone.utc),
    )
    users = [
        User(
            id="user-exdir",
            display_name="Col Smith",
            email="col.smith@example.test",
            role=UserRole.EXERCISE_DIRECTOR,
            organization="Bridgeport EXCON",
        ),
        User(
            id="user-intel-chief",
            display_name="Maj Alvarez",
            email="intel.chief@example.test",
            role=UserRole.INTELLIGENCE_CHIEF,
            organization="Intelligence Cell",
        ),
        User(
            id="user-controller",
            display_name="Capt Nguyen",
            email="controller.one@example.test",
            role=UserRole.CONTROLLER,
            organization="White Cell",
        ),
        User(
            id="user-reviewer",
            display_name="Maj Warren",
            email="reviewer.one@example.test",
            role=UserRole.REVIEWER,
            organization="Review Cell",
        ),
        User(
            id="user-media",
            display_name="Capt Brooks",
            email="media.controller@example.test",
            role=UserRole.CONTROLLER,
            organization="Media Cell",
        ),
        User(
            id="user-weather",
            display_name="1stLt Pierce",
            email="weather.controller@example.test",
            role=UserRole.CONTROLLER,
            organization="Weather Cell",
        ),
        User(
            id="user-cyber",
            display_name="Capt Kim",
            email="cyber.controller@example.test",
            role=UserRole.CONTROLLER,
            organization="Cyber Cell",
        ),
    ]
    injects = [
        Inject(
            id="inject-001",
            exercise_id=exercise.id,
            title="IED Discovery",
            description="Blue force patrol discovers simulated IED indicator near route checkpoint.",
            inject_type=InjectType.OPERATIONS,
            priority=InjectPriority.CRITICAL,
            status=InjectStatus.DRAFT,
            assigned_controller="user-controller",
            created_by="user-controller",
        ),
        Inject(
            id="inject-002",
            exercise_id=exercise.id,
            title="Civilian Protest",
            description="Role players report civilian protest activity near the training audience route.",
            inject_type=InjectType.EXERCISE_CONTROL,
            priority=InjectPriority.HIGH,
            status=InjectStatus.PENDING_REVIEW,
            assigned_controller="user-controller",
            created_by="user-controller",
        ),
        Inject(
            id="inject-003",
            exercise_id=exercise.id,
            title="Media Interview",
            description="Simulated journalist requests statement from unit public affairs representative.",
            inject_type=InjectType.MEDIA,
            priority=InjectPriority.MEDIUM,
            status=InjectStatus.APPROVED,
            assigned_controller="user-media",
            created_by="user-media",
            approved_by="user-reviewer",
        ),
        Inject(
            id="inject-004",
            exercise_id=exercise.id,
            title="GPS Interference",
            description="Cyber cell reports localized simulated GPS interference.",
            inject_type=InjectType.OTHER,
            priority=InjectPriority.HIGH,
            status=InjectStatus.SCHEDULED,
            assigned_controller="user-cyber",
            scheduled_time=datetime(2027, 3, 27, 9, 35, tzinfo=timezone.utc),
            created_by="user-cyber",
            approved_by="user-reviewer",
        ),
        Inject(
            id="inject-005",
            exercise_id=exercise.id,
            title="Drone Reconnaissance",
            description="Intelligence controller releases notional UAS sighting report.",
            inject_type=InjectType.INTELLIGENCE,
            priority=InjectPriority.MEDIUM,
            status=InjectStatus.APPROVED,
            assigned_controller="user-intel-chief",
            created_by="user-intel-chief",
            approved_by="user-reviewer",
        ),
        Inject(
            id="inject-006",
            exercise_id=exercise.id,
            title="Avalanche Warning",
            description="Weather cell issues avalanche risk update for high-angle movement corridor.",
            inject_type=InjectType.LOGISTICS,
            priority=InjectPriority.HIGH,
            status=InjectStatus.SCHEDULED,
            assigned_controller="user-weather",
            scheduled_time=datetime(2027, 3, 27, 9, 5, tzinfo=timezone.utc),
            created_by="user-weather",
            approved_by="user-reviewer",
        ),
        Inject(
            id="inject-007",
            exercise_id=exercise.id,
            title="Vehicle Breakdown",
            description="Lead vehicle reports cold-weather mechanical fault.",
            inject_type=InjectType.LOGISTICS,
            priority=InjectPriority.MEDIUM,
            status=InjectStatus.COMPLETED,
            assigned_controller="user-controller",
            scheduled_time=datetime(2027, 3, 27, 8, 25, tzinfo=timezone.utc),
            created_by="user-controller",
            approved_by="user-reviewer",
        ),
        Inject(
            id="inject-008",
            exercise_id=exercise.id,
            title="Medical Evacuation",
            description="Role player injury drives MEDEVAC coordination inject.",
            inject_type=InjectType.OPERATIONS,
            priority=InjectPriority.CRITICAL,
            status=InjectStatus.PENDING_REVIEW,
            assigned_controller="user-controller",
            created_by="user-controller",
        ),
    ]
    timeline_events = [
        TimelineEvent(
            id="timeline-001",
            exercise_id=exercise.id,
            event_type=TimelineEventType.EXERCISE_PHASE,
            title="Exercise Begins",
            description="Mountain Exercise 3-27 begins under Bridgeport EXCON control.",
            timestamp=datetime(2027, 3, 27, 8, 0, tzinfo=timezone.utc),
            source="exercise_control",
        ),
        TimelineEvent(
            id="timeline-002",
            exercise_id=exercise.id,
            event_type=TimelineEventType.INJECT,
            title="Intel Product Published",
            description="Intelligence update published to support training audience decision cycle.",
            timestamp=datetime(2027, 3, 27, 8, 10, tzinfo=timezone.utc),
            source="intelligence_cell",
            related_inject_id="inject-005",
        ),
        TimelineEvent(
            id="timeline-003",
            exercise_id=exercise.id,
            event_type=TimelineEventType.INJECT,
            title="Civilian Protest Inject",
            description="Role player protest inject sent to White Cell review lane.",
            timestamp=datetime(2027, 3, 27, 8, 25, tzinfo=timezone.utc),
            source="white_cell",
            related_inject_id="inject-002",
        ),
        TimelineEvent(
            id="timeline-004",
            exercise_id=exercise.id,
            event_type=TimelineEventType.INJECT,
            title="Cyber Event",
            description="Cyber controller reports simulated GPS interference.",
            timestamp=datetime(2027, 3, 27, 8, 40, tzinfo=timezone.utc),
            source="cyber_cell",
            related_inject_id="inject-004",
        ),
        TimelineEvent(
            id="timeline-005",
            exercise_id=exercise.id,
            event_type=TimelineEventType.NOTE,
            title="Weather Update",
            description="Weather controller updates avalanche risk and visibility conditions.",
            timestamp=datetime(2027, 3, 27, 9, 5, tzinfo=timezone.utc),
            source="weather_cell",
            related_inject_id="inject-006",
        ),
        TimelineEvent(
            id="timeline-006",
            exercise_id=exercise.id,
            event_type=TimelineEventType.NOTE,
            title="Blue Force Movement",
            description="Blue force report received and added to common operational picture.",
            timestamp=datetime(2027, 3, 27, 9, 20, tzinfo=timezone.utc),
            source="blue_force_report",
        ),
        TimelineEvent(
            id="timeline-007",
            exercise_id=exercise.id,
            event_type=TimelineEventType.INJECT,
            title="Media Inject",
            description="Approved media interview inject staged.",
            timestamp=datetime(2027, 3, 27, 9, 35, tzinfo=timezone.utc),
            source="media_cell",
            related_inject_id="inject-003",
        ),
        TimelineEvent(
            id="timeline-008",
            exercise_id=exercise.id,
            event_type=TimelineEventType.NOTE,
            title="Commander Decision",
            description="Commander decision point logged for after-action review.",
            timestamp=datetime(2027, 3, 27, 9, 40, tzinfo=timezone.utc),
            source="exercise_director",
        ),
    ]
    review_items = [
        StudioReviewItem(
            id="review-001",
            exercise_id=exercise.id,
            item_type=ReviewItemType.INJECT,
            item_id="inject-002",
            status=StudioReviewStatus.PENDING,
            reviewer_id="user-reviewer",
        ),
        StudioReviewItem(
            id="review-002",
            exercise_id=exercise.id,
            item_type=ReviewItemType.PRODUCT,
            item_id="product-intel-update-001",
            status=StudioReviewStatus.IN_REVIEW,
            reviewer_id="user-reviewer",
            comments="Checking source traceability.",
        ),
        StudioReviewItem(
            id="review-003",
            exercise_id=exercise.id,
            item_type=ReviewItemType.INJECT,
            item_id="inject-008",
            status=StudioReviewStatus.PENDING,
            reviewer_id="user-reviewer",
        ),
    ]
    audit_logs = [
        AuditLog(
            id="audit-001",
            exercise_id=exercise.id,
            actor_id="user-exdir",
            action="exercise.phase.updated",
            target_type="exercise",
            target_id=exercise.id,
            timestamp=datetime(2027, 3, 27, 8, 0, tzinfo=timezone.utc),
            metadata={"phase": ExercisePhase.EXECUTION.value},
        ),
        AuditLog(
            id="audit-002",
            exercise_id=exercise.id,
            actor_id="user-controller",
            action="inject.review.submitted",
            target_type="inject",
            target_id="inject-002",
            timestamp=datetime(2027, 3, 27, 8, 25, tzinfo=timezone.utc),
            metadata={"status": InjectStatus.PENDING_REVIEW.value},
        ),
    ]

    return ForgeStudioRegistry(
        exercises=[exercise],
        users=users,
        injects=injects,
        timeline_events=timeline_events,
        review_items=review_items,
        audit_logs=audit_logs,
    )


def create_mock_workspace() -> dict[str, object]:
    """Create non-model UI data for the interactive Forge Studio demo."""

    return {
        "exercise": {
            "id": "mountain-exercise-3-27",
            "name": "Mountain Exercise 3-27",
            "status": "ACTIVE",
            "phase": "EXECUTE",
            "start": "0800",
            "exercise_director": "Col Smith",
            "exercise_control": "Bridgeport EXCON",
            "health": "Nominal",
            "operational_time": "0942",
            "training_audience": "2d Battalion, 8th Marines",
            "timeline_status": "On Plan",
            "objectives": [
                "Exercise command and control in complex mountain terrain.",
                "Evaluate intelligence-to-operations handoff under time pressure.",
                "Validate casualty evacuation and route disruption procedures.",
                "Assess media, cyber, and weather inject response.",
            ],
            "participating_units": [
                "2d Battalion, 8th Marines",
                "Mountain Warfare Training Center",
                "Bridgeport EXCON",
                "Blue Force Role Players",
                "Simulated Media Cell",
            ],
            "statistics": [
                {"label": "Injects", "value": "8"},
                {"label": "Products", "value": "12"},
                {"label": "Reviews", "value": "3"},
                {"label": "Timeline Events", "value": "8"},
            ],
        },
        "activity": [
            {"time": "0937", "title": "Intelligence Update Published"},
            {"time": "0935", "title": "Cyber Inject Approved"},
            {"time": "0931", "title": "Media Story Released"},
            {"time": "0926", "title": "Weather Updated"},
            {"time": "0920", "title": "Blue Force Report Received"},
        ],
        "controllers": [
            {
                "role": "Exercise Director",
                "name": "Col Smith",
                "task": "Commander decision point review",
                "status": "Online",
                "products_today": 2,
                "pending_reviews": 1,
            },
            {
                "role": "Intelligence Controller",
                "name": "Maj Alvarez",
                "task": "Intel update validation",
                "status": "Online",
                "products_today": 4,
                "pending_reviews": 1,
            },
            {
                "role": "White Cell Controller",
                "name": "Capt Nguyen",
                "task": "Civilian protest inject",
                "status": "Online",
                "products_today": 2,
                "pending_reviews": 2,
            },
            {
                "role": "Media Controller",
                "name": "Capt Brooks",
                "task": "Media interview release",
                "status": "Online",
                "products_today": 3,
                "pending_reviews": 0,
            },
            {
                "role": "Weather Controller",
                "name": "1stLt Pierce",
                "task": "Avalanche warning update",
                "status": "Online",
                "products_today": 2,
                "pending_reviews": 0,
            },
            {
                "role": "Cyber Controller",
                "name": "Capt Kim",
                "task": "GPS interference inject",
                "status": "Online",
                "products_today": 1,
                "pending_reviews": 0,
            },
            {
                "role": "Role Player Controller",
                "name": "GySgt Miller",
                "task": "Civilian protest cell",
                "status": "Monitoring",
                "products_today": 0,
                "pending_reviews": 0,
            },
        ],
        "library_folders": [
            "Intelligence",
            "Injects",
            "Media",
            "Weather",
            "Reports",
            "Maps",
            "Photos",
            "Video",
            "Documents",
            "Exports",
        ],
        "products": [
            {
                "type": "Intelligence",
                "title": "Intelligence Update 001",
                "status": "Published",
                "version": "v1.2",
                "updated": "0937",
                "author": "Maj Alvarez",
                "review": "Approved",
            },
            {
                "type": "Inject",
                "title": "GPS Interference",
                "status": "Scheduled",
                "version": "v1.0",
                "updated": "0935",
                "author": "Capt Kim",
                "review": "Approved",
            },
            {
                "type": "Media",
                "title": "Local Media Story",
                "status": "Released",
                "version": "v2.0",
                "updated": "0931",
                "author": "Capt Brooks",
                "review": "Approved",
            },
            {
                "type": "Weather",
                "title": "Avalanche Warning",
                "status": "Published",
                "version": "v1.1",
                "updated": "0926",
                "author": "1stLt Pierce",
                "review": "Approved",
            },
            {
                "type": "Report",
                "title": "Blue Force Movement Report",
                "status": "Filed",
                "version": "v1.0",
                "updated": "0920",
                "author": "Capt Nguyen",
                "review": "Logged",
            },
            {
                "type": "Map",
                "title": "Route Hawk Overlay",
                "status": "Current",
                "version": "v3.4",
                "updated": "0915",
                "author": "Bridgeport EXCON",
                "review": "Approved",
            },
        ],
        "settings": [
            {
                "title": "Organization",
                "description": "Bridgeport EXCON ownership, cells, and exercise command metadata.",
            },
            {
                "title": "Exercise Defaults",
                "description": "Default phase labels, timeline start, review gates, and archive policy.",
            },
            {
                "title": "Appearance",
                "description": "Dark command-center theme, Forge orange accents, and density controls.",
            },
            {
                "title": "Notifications",
                "description": "Review alerts, timeline changes, controller handoff, and system health.",
            },
            {
                "title": "Users",
                "description": "Controller roster, reviewer assignments, observers, and administrators.",
            },
            {
                "title": "Integrations",
                "description": "Local-only dry-run integrations reserved for future approved connectors.",
            },
            {
                "title": "AI Providers",
                "description": "Offline stub configuration and future bounded provider controls.",
            },
            {
                "title": "Plugins",
                "description": "Product plugins, profile packages, and workflow module readiness.",
            },
            {
                "title": "Audit",
                "description": "Complete audit trail, activity feed retention, and export controls.",
            },
        ],
    }
